update default profile / templates to match latest artemis default configuration
rh-messaging-qe/yacfg_artemis pull request #1
Opened 2023-02-08 19:48 UTC by tlbueno

@enkeys / @michalxo this PR contains the updates related to the default profile / templates.

With these changes all default configuration that `artemis create` command currently has (2.18.0) when it generates the configuration files are now included.

Basically I tried to keep the files as close as possible with the default ones generated by artemis, so in the future we can easily spot changes in the default configuration.

Since this is my 1st PR in this repo please take a close look and let me know if you think I should change something.

2023-02-09 07:33 UTC, michalxo commented
Personally I don't like having commented code in template (imo it does not make sense, cause you know what you are doing and what deployment you want). And you're not going to perform diff there..

Else I would say this PR is fine.

2023-02-09 07:35 UTC, michalxo approved these changes
Consider removing commented code. Else OK

2023-02-09 11:55 UTC, tlbueno commented
> Personally I don't like having commented code in template (imo it does not make sense, cause you know what you are doing and what deployment you want). And you're not going to perform diff there..
> 
> Else I would say this PR is fine.

I have mixed feelings about keep the comments or not but thinking a bit more about it removing it will generate a file which is clean and simple. 

Also I just use a diff locally to ensure the default configuration options and its values are in sync with the one generated by the artemis cli create command, so, keeping the file structure in the same order but remove the comments will not make the diff check so hard since it is only comments.

So, I will remove the comments

2023-02-09 13:12 UTC, tlbueno commented
PR updated. the comments in the files generated are removed.

2023-02-09 23:01 UTC, enkeys requested changes

2023-02-09 23:01 UTC, enkeys commented on profiles/artemis/_modules/artemis_profile/default.yaml.jinja2
> -    - -XX:+HeapDumpOnOutOfMemoryError
Removing this from the default profile is probably a good reason it's not the default. But we should probably create some other profile that allows/include it.

2023-02-09 23:04 UTC, enkeys commented
> Personally I don't like having commented code in template (imo it does not make sense, cause you know what you are doing and what deployment you want). And you're not going to perform diff there..
> 
> Else I would say this PR is fine.

@michalxo @tlbueno The commented code was there because we wanted to provide a default 1:1 configuration with ActiveMQ Artemis.

2023-02-09 23:16 UTC, enkeys commented on templates/libs/headers/generator_notice.jinja2
> +This configuration file {{ metadata.out_filename }} has been generated
never mind, now I saw that it generates a long line

2023-02-13 11:42 UTC, tlbueno commented on templates/artemis/broker.xml.jinja2
> +      <!-- Uncomment the following if you want to use the Standard LoggingActiveMQServerPlugin pluging to log in events
I didn´t understand you comment here

2023-02-13 11:43 UTC, tlbueno commented on profiles/artemis/default.yaml.jinja2
> -  large_messages_directory: data/large-messages
I moved it inside the journal configuration

2023-02-13 11:43 UTC, tlbueno commented on templates/artemis/modules/broker_xml/queue.jinja2
>  {# DON'T TOUCH THE INDENTATION !!! #}
yes, but the formatting was not matching with the one generated by artemis cli. so, I did just a small indentation fix to match

2023-02-13 11:46 UTC, tlbueno commented on templates/artemis/broker.xml.jinja2
> -        {% include 'modules/broker_xml/critical_analyzer.jinja2' %}
just moved up in the configuration

2023-02-13 11:46 UTC, tlbueno commented on profiles/artemis/_modules/artemis_profile/default.yaml.jinja2
> -    - -XX:+HeapDumpOnOutOfMemoryError
ok. I can create a new one for this later.

2023-02-13 12:57 UTC, enkeys commented on templates/artemis/modules/broker_xml/queue.jinja2
>  {# DON'T TOUCH THE INDENTATION !!! #}
👍

2023-02-13 12:58 UTC, enkeys commented on profiles/artemis/default.yaml.jinja2
> -  large_messages_directory: data/large-messages
👍  Yeah, I hadn't noticed that either.

2023-02-13 12:58 UTC, enkeys commented on templates/artemis/broker.xml.jinja2
> -        {% include 'modules/broker_xml/critical_analyzer.jinja2' %}
Yeah, I hadn't noticed that either.

2023-02-13 13:00 UTC, enkeys approved these changes

2023-02-13 15:47 UTC, tlbueno commented
for some reason this PR still open after merging it. So, I am going to close it.

2023-02-13 15:47 UTC, closed without merging